### ISSUE TITLE
`pip install -e .` fails

### ISSUE THREAD

**Issue by bendecoste** [mortendahl/tf-encrypted#133]
During setup

```
Exception:
Traceback (most recent call last):
  File "/Users/bendecoste/anaconda3/envs/tf-encrypted/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 483, in check_if_exists
    self.satisfied_by = pkg_resources.get_distribution(str(no_marker))
  File "/Users/bendecoste/anaconda3/envs/tf-encrypted/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 468, in get_distribution
    dist = get_provider(dist)
  File "/Users/bendecoste/anaconda3/envs/tf-encrypted/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 344, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/Users/bendecoste/anaconda3/envs/tf-encrypted/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/bendecoste/anaconda3/envs/tf-encrypted/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pip._vendor.pkg_resources.ContextualVersionConflict: (numpy 1.15.1 (/Users/bendecoste/anaconda3/envs/tf-encrypted/lib/python3.6/site-packages), Requirement.parse('numpy<=1.14.5,>=1.13.3'), {'tensorflow'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bendecoste/anaconda3/envs/tf-encrypted/lib/python3.6/site-packages/pip/_internal/basecommand.py", line 141, in main
    status = self.run(options, args)
  File "/Users/bendecoste/anaconda3/envs/tf-encrypted/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 299, in run
    resolver.resolve(requirement_set)
  File "/Users/bendecoste/anaconda3/envs/tf-encrypted/lib/python3.6/site-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/Users/bendecoste/anaconda3/envs/tf-encrypted/lib/python3.6/site-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Users/bendecoste/anaconda3/envs/tf-encrypted/lib/python3.6/site-packages/pip/_internal/resolve.py", line 193, in _get_abstract_dist_for
    req, self.require_hashes, self.use_user_site, self.finder,
  File "/Users/bendecoste/anaconda3/envs/tf-encrypted/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 329, in prepare_editable_requirement
    req.check_if_exists(use_user_site)
  File "/Users/bendecoste/anaconda3/envs/tf-encrypted/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 494, in check_if_exists
    self.req.name
  File "/Users/bendecoste/anaconda3/envs/tf-encrypted/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 468, in get_distribution
    dist = get_provider(dist)
  File "/Users/bendecoste/anaconda3/envs/tf-encrypted/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 344, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/Users/bendecoste/anaconda3/envs/tf-encrypted/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/bendecoste/anaconda3/envs/tf-encrypted/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pip._vendor.pkg_resources.ContextualVersionConflict: (numpy 1.15.1 (/Users/bendecoste/anaconda3/envs/tf-encrypted/lib/python3.6/site-packages), Requirement.parse('numpy<=1.14.5,>=1.13.3'), {'tensorflow'})
```

**Comment by justin1121** [comment]
I think this is a problem with your environment. You have numpy 1.15.1 installed but tf-encrypted requires less than 1.14.5. Should probably do stuff in a new environment. Or maybe we should accept any version of numpy?!

**Comment by justin1121** [comment]
Hey @vishwajit123. We've recently implemented a custom operation for tensorflow so that we can securely generate random numbers. This custom operation is written in C++ so it must first be built when you're installing tf-encrypted for development. This is hinted at by the error here:

```
Exception: Could not find the secure random shared object for the installed tensorflow version 1.11.0
```

So a secure random shared object needs to be built first for your installed version of tensorflow. Before digging deeper into this issue it'd be great to know if you were able to get this shared object built. You can usually find it in the `tf-encrypted/tf_encrypted/operations/secure_random/` folder and will look something like `secure_random_module_tf_1.11.0.so`.

**Comment by justin1121** [comment]
Glad you got it figured out! Cheers!
