### ISSUE TITLE
TypeError: Forward references must evaluate to types. Got tf.int64.

### ISSUE THREAD

**Issue by mkskeller** [mortendahl/tf-encrypted#376]
Despite installing the wheel linked to in the readme, I get the following error on Ubuntu 16.04 (on Ubuntu 18.04 the wheel would install at all):
```
Traceback (most recent call last):
  File "./examples/mnist/run.py", line 5, in <module>
    import tf_encrypted as tfe
  File "/home/marcel/.local/lib/python3.5/site-packages/tf_encrypted/__init__.py", line 7, in <module>
    from .session import Session, setTFEDebugFlag, setMonitorStatsFlag, setTFETraceFlag
  File "/home/marcel/.local/lib/python3.5/site-packages/tf_encrypted/session.py", line 11, in <module>
    from .protocol.pond import PondPublicTensor
  File "/home/marcel/.local/lib/python3.5/site-packages/tf_encrypted/protocol/__init__.py", line 5, in <module>
    from .securenn import SecureNN
  File "/home/marcel/.local/lib/python3.5/site-packages/tf_encrypted/protocol/securenn/__init__.py", line 3, in <module>
    from .securenn import SecureNN
  File "/home/marcel/.local/lib/python3.5/site-packages/tf_encrypted/protocol/securenn/securenn.py", line 10, in <module>
    from .odd_tensor import oddInt64factory
  File "/home/marcel/.local/lib/python3.5/site-packages/tf_encrypted/protocol/securenn/odd_tensor.py", line 14, in <module>
    class OddImplicitFactory:
  File "/home/marcel/.local/lib/python3.5/site-packages/tf_encrypted/protocol/securenn/odd_tensor.py", line 16, in OddImplicitFactory
    def __init__(self, native_type: Union[Type['tf.int32'], Type['tf.int64']]) -> None:
  File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "/usr/lib/python3.5/typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 1059, in __subclasscheck__
    if not issubclass(p_cls, p_self):
  File "/usr/lib/python3.5/typing.py", line 190, in __subclasscheck__
    self._eval_type(globalns, localns)
  File "/usr/lib/python3.5/typing.py", line 178, in _eval_type
    "Forward references must evaluate to types.")
  File "/usr/lib/python3.5/typing.py", line 312, in _type_check
    raise TypeError(msg + " Got %.100r." % (arg,))
TypeError: Forward references must evaluate to types. Got tf.int64.
```

**Comment by mortendahl** [comment]
Taking a look, thanks for reporting!

**Comment by mortendahl** [comment]
Installing from source code instead of pip package now works on Ubuntu 16.04 and 18.04.

Install:
```sh
./ $ git clone https://github.com/mortendahl/tf-encrypted.git
./ $ cd tf-encrypted
./tf-encrypted/ $ pip3 install -e .
```

Run [MNIST example](./examples/mnist/):
```sh
./tf-encrypted/ $ python3 examples/mnist/download.py
./tf-encrypted/ $ python3 examples/mnist/run.py
```

Mind giving it a try @mkskeller?

**Comment by mortendahl** [comment]
See also #386 which added extra installation documentation

**Comment by mortendahl** [comment]
Closing following offline communications
